# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
myList=s.split()
print(myList)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [6]:
print('The diameter of the {} is {}km'.format(planet, diameter))

The diameter of the Earth is 12742km


## 3. In this nest dictionary grab the word "hello"

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [9]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [15]:
array_zeros = np.zeros((10), dtype=int)
print(f"Array of Zeros: \n{array_zeros}")

Array of Zeros: 
[0 0 0 0 0 0 0 0 0 0]


In [14]:
array_fives = np.ones((10), dtype=int) * 5
print(f"Array of Fives: \n{array_fives}")

Array of Fives: 
[5 5 5 5 5 5 5 5 5 5]


## 5. Create an array of all the even integers from 20 to 35

In [16]:
array_even_integers = np.arange(20, 35, 2)
print(f"Even Array: \n{array_even_integers}")

Even Array: 
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
user_matrix = np.arange(9).reshape(3, 3)
print(f"3x3 Matrix: \n{user_matrix}")

3x3 Matrix: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate((a, b), axis=None))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [24]:
import pandas as pd


In [26]:
# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]
  
data = {'Name':['aaa', 'bbb', 'ccc'], 'Age':[20, 20, 21]} 
print(data)

{'Name': ['aaa', 'bbb', 'ccc'], 'Age': [20, 20, 21]}


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [27]:
series=pd.date_range(start='01-jan-2023',end='10-feb-2023')
print(series)


DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [28]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [29]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25]]
ls=pd.DataFrame(lists,columns=['S.No','Name','Age'])
print(ls)

   S.No Name  Age
0     1  aaa   22
1     2  bbb   25
